### ISSUE TITLE
Migrate Schemas command attempts to migrate tenant apps on public schema

### ISSUE THREAD

**Issue by k0nG** [bernardopires/django-tenant-schemas#231] opened 2015-01-31 13:57 UTC
Thanks for to everyone who worked on the updates for 1.7 compatibility. 

I've come across an issue with tenant app migrations being attempted to run against the public schema. 

I've created a migration for an app that i've specified **only** in `TENANT_APPS`. However when I run `migrate_schemas` Django's migration system tries to run this migrations on the public schema. This then causes a sql error as the table doesn't exist in that schema. 

I'm not sure why the initial migration wasn't run before on the public schemas, it must of been faked somehow when the pubic schema was created?

I've taken a look at the migration code and I can that there is a `included_apps` argument in on the `run_migrations` method (https://github.com/bernardopires/django-tenant-schemas/blob/master/tenant_schemas/management/commands/migrate_schemas.py#L47). That argument isn't used despite the conditions above trying to determine what apps to use.

I can't see an obvious solution. As looking at the Django migration code unless it is passed a single app label it will migrate all available apps with migrations.
 
So I guess that's why `included_apps` isn't used? Perhaps that was a known limitation of the 1.7 compatibility updates?

**Comment by P0oky** [comment] 2015-02-25 21:00
I was getting the same error. It turns out to be because I was using some migration.RunSQL operations. Specifically, I was creating some tables then updating their permissions.

The problem is in the django migration operations - migrations.CreateModel correctly checks with the router to see if it is allowed to act, but RunPython and RunSQL don't do this check. In this case, the router is the custom one from from this project that makes sure the migrations run in the proper schemas. I've looked at the code base, those operations seem to be fixed in 1.8. But until that is released and supported, here is my workaround:

The code that was broken:

    from django.db import models, migrations
    
    class Migration(migrations.Migration):
        operations = [
            migrations.CreateModel( name="my_table", ... ),
            migrations.RunSQL( "grant select on my_table to otheruser;" )    # this was the problem, it was getting run in the public schema
        ]

and here is my workaround:

    from django.db import models, migrations
    from tenant_schemas.utils import get_public_schema_name
    
    def grant( apps, schema_editor ):
        # This is the magic, don't run on public:
        if schema_editor.connection.schema_name != get_public_schema_name():
            schema_editor.execute( 'grant all on my_table to otheruser;', params=None )

    class Migration(migrations.Migration):
        operations = [
            migrations.CreateModel( name='my_table', ... ),
            migrations.RunPython( grant ),
        ]

hope that helps.

**Comment by k0nG** [comment] 2015-02-26 08:49
Thanks I'll give that a try.

**Comment by k0nG** [comment] 2015-04-02 08:46
Just looking at the Django 1.8 release notes. It talks of a new `allow_migrate` function on the database router. This could perhaps solve this issue?

"The migration operations RunPython and RunSQL now call the allow_migrate() method of database routers. The router can use the newly introduced app_label and hints arguments to make a routing decision. To take advantage of this feature you need to update the router to the new allow_migrate signature, see the deprecation section for more details."
https://docs.djangoproject.com/en/1.8/releases/1.8/#migrations

**Comment by k0nG** [comment] 2015-04-02 08:56
Actually I can see that's already been implemented for 1.7. https://github.com/bernardopires/django-tenant-schemas/blob/master/tenant_schemas/routers.py#L10

**Closed** 2015-09-04 15:43 UTC
