### ISSUE TITLE
Rendering model states slows down migrations

### ISSUE THREAD

**Issue by w0rp** [bernardopires/django-tenant-schemas#415] opened 2016-12-08 11:00 UTC
When migrations are run with many tenants, the part which seems to take the longest time in my experience is the stage of migrations where Django has to determine which migrations to apply. The "rendering model states" step.

Is there anything which can be done to speed up this process? If you have 200 schemas, all of which need to have the same exact migrations applied to them, the time spent on that part of the migration process takes a huge chunk of time. If that cost was cut down significantly, then the time needed to run the migrations would also be reduced significantly.

I wonder if some kind of memoization can be performed to solve this.

**Comment by AlexvEck** [comment] 2016-12-29 09:05
This is a duplicate of #387 and can be fixed with PR #391

**Comment by bernardopires** [comment] 2017-05-06 12:16
Closing as it was fixed in #454

**Closed by bernardopires** 2017-05-06 12:16 UTC
