### ISSUE TITLE
Getting field error after configuring the package. ( FieldError at / )

### ISSUE THREAD

**Issue by gurmindersingh42** [bernardopires/django-tenant-schemas#376] opened 2016-08-29 12:27 UTC
Hello Support,

We have installed the django-tennat-schemas and and configured it as per the documentation. Before installation the website was working fine for the public schemas and after the installation and running the migrations, it start giving the error.
Error is:
FieldError at /

Cannot resolve keyword 'domain_url' into field. 

Is there any change in the urls.py for managing the urls.
Here is the urls.py 

urlpatterns = [
    #url(r'^polls/', include('polls.urls')),
    #url(r'^home/', include('users.urls')),
    #url(r'^home/', include('users.urls')),
    #url(r'^home/$', home),
    url(r'^admin/', admin.site.urls),
    #url(r'^$', include('users.urls')),  #main site  home page
    url(r'^$', home),
    url(r'^signup', signup, name='signup'),
    url(r'^login', user_login, name='login'),
    url(r'^forgotpassword', forgot_password, name='forgotpassword'),
    url(r'^create_school', create_school, name='create_school'),
    url(r'^create_language', create_language, name='create_language'),
    url(r'^resetpassword', reset_password, name='resetpassword'),
    url(r'^logout', logout_page, name='logout'),
    url(r'^sliders/', include('sliders.urls')),
    url(r'^slider', slider, name='slider'),
    url(r'^profile', profile, name='profile'),
]

Please let me know , what can i do with make it working.

Thanks.

**Comment by bernardopires** [comment] 2016-10-01 16:39
This is really insufficient information to debug what the problem is. You can paste your settings.py file here if you want and I'll take look. I recommend you to just follow the docs though. Closing this for now, feel free to reopen!

**Closed by bernardopires** 2016-10-01 16:39 UTC
Labels: question

**Comment by PT1381129** [comment] 2020-09-04 07:05
> This is really insufficient information to debug what the problem is. You can paste your settings.py file here if you want and I'll take look. I recommend you to just follow the docs though. Closing this for now, feel free to reopen!

I am getting the same issue while accessing tenant or public schema URLs from the browser, I have created Client and Domain classes for tenant_schemas, migrated successfully. 

 **FieldError at /
[base.txt](https://github.com/bernardopires/django-tenant-schemas/files/5173197/base.txt)

Cannot resolve keyword 'domain_url' into field. Choices are: created_on, domains, id, name, schema_name, subscription_type**
